using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/Anima")]
public partial class Anima : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4802917719616922041UL,2075980587229156253UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public new System.String name
	{
		get => _name[Entity.Index];
		set => _name[Entity.Index] = value;
	}
	public System.Single Stamina
	{
		get => _Stamina[Entity.Index];
		set => _Stamina[Entity.Index] = value;
	}
	public System.Single Damage
	{
		get => _Damage[Entity.Index];
		set => _Damage[Entity.Index] = value;
	}
	public System.Single Speed
	{
		get => _Speed[Entity.Index];
		set => _Speed[Entity.Index] = value;
	}
	public System.Single DropRate
	{
		get => _DropRate[Entity.Index];
		set => _DropRate[Entity.Index] = value;
	}
	public System.Int32 DropGold
	{
		get => _DropGold[Entity.Index];
		set => _DropGold[Entity.Index] = value;
	}
	public System.String Objectfile
	{
		get => _Objectfile[Entity.Index];
		set => _Objectfile[Entity.Index] = value;
	}
	public System.String Image
	{
		get => _Image[Entity.Index];
		set => _Image[Entity.Index] = value;
	}
	public System.String Type
	{
		get => _Type[Entity.Index];
		set => _Type[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5712815074438004680UL, 5534772356683341238UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Stamina;
	public static BansheeGz.BGDatabase.BGFieldFloat _Stamina => _ufle12jhs77_Stamina ?? (_ufle12jhs77_Stamina = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5062393703014930942UL, 8018071100970199709UL), () => _ufle12jhs77_Stamina = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Damage;
	public static BansheeGz.BGDatabase.BGFieldFloat _Damage => _ufle12jhs77_Damage ?? (_ufle12jhs77_Damage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5305809400655546658UL, 13939413414334458547UL), () => _ufle12jhs77_Damage = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_Speed;
	public static BansheeGz.BGDatabase.BGFieldFloat _Speed => _ufle12jhs77_Speed ?? (_ufle12jhs77_Speed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4632003650934578460UL, 11781341433753260948UL), () => _ufle12jhs77_Speed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_DropRate;
	public static BansheeGz.BGDatabase.BGFieldFloat _DropRate => _ufle12jhs77_DropRate ?? (_ufle12jhs77_DropRate = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4669182272304318911UL, 18246778292411396026UL), () => _ufle12jhs77_DropRate = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_DropGold;
	public static BansheeGz.BGDatabase.BGFieldInt _DropGold => _ufle12jhs77_DropGold ?? (_ufle12jhs77_DropGold = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5379282569970594670UL, 1917782598661563271UL), () => _ufle12jhs77_DropGold = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Objectfile;
	public static BansheeGz.BGDatabase.BGFieldString _Objectfile => _ufle12jhs77_Objectfile ?? (_ufle12jhs77_Objectfile = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5563748492139597177UL, 5065189666584222359UL), () => _ufle12jhs77_Objectfile = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Image;
	public static BansheeGz.BGDatabase.BGFieldString _Image => _ufle12jhs77_Image ?? (_ufle12jhs77_Image = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4732492147341155909UL, 8403525512104126366UL), () => _ufle12jhs77_Image = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Type;
	public static BansheeGz.BGDatabase.BGFieldString _Type => _ufle12jhs77_Type ?? (_ufle12jhs77_Type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5405294115762679379UL, 7367137605929633922UL), () => _ufle12jhs77_Type = null));
}
